# Generated by Django 2.1.7 on 2019-05-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20190526_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.AddField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
