# Generated by Django 2.1.7 on 2019-05-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20190528_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nick_name',
        ),
    ]
